name: Update README Activity

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update activity section
        uses: jamesgeorge007/github-activity-readme@v0.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
